export const FETCH_MOVIES_LIST_REQUEST = 'FETCH_MOVIES_LIST';
export const FETCH_MOVIES_LIST_SUCCESS = 'FETCH_MOVIES_LIST_SUCCESS';
export const FETCH_MOVIES_LIST_FAILURE = 'FETCH_MOVIES_LIST_FAILURE';
export const CHANGE_SORTING = 'CHANGE_SORTING';
export const CHANGE_FILTERING = 'CHANGE_FILTERING';
export const CHANGE_MOVIES_LIST = 'CHANGE_MOVIES_LIST';
