export const FETCH_MOVIES_LIST_REQUEST = 'FETCH_MOVIES_LIST';
export const FETCH_MOVIES_LIST_SUCCESS = 'FETCH_MOVIES_LIST_SUCCESS';
export const FETCH_MOVIES_LIST_FAILURE = 'FETCH_MOVIES_LIST_FAILURE';
